### ISSUE TITLE
Add graphics scaling

### ISSUE THREAD

**Issue by bit-hack** [8BitPimp/scummvm#1]
The current 1:1 pixel scale makes it hard to spot many visual problems.
- Implement 2x and 3x upscalers.
- Integrate these scalars into the UI so they can be selected.
- Do not forget to add compensation scale to mouse position.

**Comment by bit-hack** [comment]
bcf6d4d0b7b5772998c8dd7784e6791fc94b5c1f

As of this commit the win32 backend has support for graphics scaling.  The scale factor is currently hard coded at 2x, and must be hooked up to the config system.  Scaling is performed via StretchDIBits() call in conjunction with GetClientRect() and a window size being a multiple of the back buffer.  A dependancy has been created between The Win32EventSource and GDIGraphicsManager as the former needs the latter to get the window scale factor for mouse position scaling.

todo:
- Attach scale factor to ScummVM config and settings.
- Check StretchDIBits() performance.

**Comment by 8BitPimp** [comment]
todo:
- Attach scale factor to ScummVM config and settings.
- Check StretchDIBit performance.

**Comment by bit-hack** [comment]
Original task is complete.  Creating a new issue to hook up the graphics scale to the ScummVM config and settings.
